### PR TITLE
Addition of a new module

### PR DESCRIPTION
**Pull request by sumukhchitloor**
#### <h1>Checklist</h1>
- [x] I have followed the [Contributor Guidelines](https://github.com/OWASP/Nettacker/wiki/Developers#contribution-guidelines).
- [x] The code has been thoroughly tested in my local development environment with flake8 and pylint.
- [x] The code is Python 3 compatible.
- [ ] The code follows the PEP8 styling guidelines with 4 spaces indentation.
- [x] This Pull Request relates to only one issue or only one feature
- [ ] I have referenced the corresponding issue number in my commit message
- [x] I have added the relevant documentation.
- [x] My branch is up-to-date with the Upstream master branch.

#### <h1>Changes proposed in this pull request</h1>

<h4>Added a new module for smb  bruteforce on ports 445 and 139 ,referenced through other modules</h4>

#### <h1>Reviewers</h1>
@Ali-Razmjoo
@securestep9

#### <h1> Your development environment</h1>
- OS: `Kali GNU/Linux Rolling`
- OS Version: `2022.4`
- Python Version: `3.10.9`

### CODE REVIEW

**Comment by itsdivyanshjain** [comment]
Have you tried to test this module on your local smb system.

**Comment by sumukhchitloor** [comment]
Yes I've tried this on my local machine ans even one of the try hackme machine

**Review by securestep9 — CHANGES_REQUESTED** [review]
@sumukhchitloor  This module is implemented incorrectly, appears it has been submitted without testing. This modules crashes with error:

**AttributeError: module 'smbprotocol' has no attribute 'SMBClient'**

SMB requires lots of additional dependencies and configuration which are missing in this PR.

Please always pull the latest version of Nettacker, test your code before submission,  include all dependencies, write unit tests and test in docker

**Comment by arkid15r** [comment]
Closing this out as inactive, feel free to reopen when it's ready.

**Pull request closed without merging**
