### PR TITLE
Update compatible.py

### PR DESCRIPTION
**Pull request by pylyf**
Trying to improve clean coding.
Not much to describe here.

#### Checklist
- [ ] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [ ] I have added the relevant documentation.
- [ ] My branch is up-to-date with the Upstream master branch.

#### Changes proposed in this pull request
Replacing `if this equal that or this equal that` with `if this in this or that`

*This makes it way shorter and nicer in my opinion.*

#### Your development environment
- OS: `Windows`
- Python Version: `3.8`

### CODE REVIEW

**Comment by pylyf** [comment]
I'm working from my mobile right now and I can't delete that whitespace. ~_~

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks for your contribution, let me check the PR and get back to you soon.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hi, according to this (https://stackoverflow.com/a/13874620), we may not work with `linux2`, anyway @shaddygarg @pradeepjairamani @cwcromwell I think it's a good time to add a matrix for tested os, I believe it will work freebsd as well.

```
.---------------------.------------.
| System              | Value      |
|---------------------|------------|
| Linux (2.x and 3.x) | linux2 (*) |
| Windows             | win32      |
| Windows/Cygwin      | cygwin     |
| Mac OS X            | darwin     |
| OS/2                | os2        |
| OS/2 EMX            | os2emx     |
| RiscOS              | riscos     |
| AtheOS              | atheos     |
| FreeBSD 7           | freebsd7   |
| FreeBSD 8           | freebsd8   |
| FreeBSD N           | freebsdN   |
'---------------------'------------'
```

**Comment by pylyf** [comment]
Pardon my dullness, but what does that mean? Should I change the code somehow or?

**Comment by Ali-Razmjoo** [comment]
@pylyf yes, the statement is not covering all supported Linux.

```
>>> import sys
>>> sys.platform
'linux2'
>>> sys.platform in ['linux','darwin']
False
>>> 'linux' in sys.platform
True
>>>
```

as I mentioned, maybe we need to list of all supported os and then check it like `if os_name() in supported_os():`

regards.

**Pull request closed without merging**
